//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class SahaRezerve
    {
        public int Id { get; set; }
        public int SahaId { get; set; }
        public string Tarih { get; set; }
        public string Saat { get; set; }
        public string Nott { get; set; }
        public string Durum { get; set; }
    }
}
