//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class SahaBilgi
    {
        public int id { get; set; }
        public string sahaAdı { get; set; }
        public string fiyat { get; set; }
        public string konum { get; set; }
        public string kapasite { get; set; }
    }
}
